const express = require('express')
const Router = express.Router()
const { authController } = require('../controller/auth')
// const { usersController } = require('../controller/users')
const { protect } = require('../middleware/auth')
// const activasi = require('../middleware/activasi')

Router.post('/login', authController.loginUser)
  .post('/register', authController.register)
  .get('/profile', protect, authController.profil)
  .post('/refreshtoken', authController.refreshToken)
  .put('/activasi/:token', authController.activasi)
  .get('/activasi/:token', authController.cekActivasi)
  .post('/changePassword', authController.changePassword)
  .post('/sendEmail', authController.sendEmail)
module.exports = Router
