const express = require('express')
const Router = express.Router()
const { usersController } = require('../controller/users')
const uploadImg = require('../middleware/upload')
const { isAdmin, protect } = require('../middleware/auth')

Router.get('/', usersController.getUsers)
  .get('/filter', usersController.getUsersByFilter)
  .get('/search', usersController.getSearchUsers)
  .post('/', isAdmin, protect, usersController.createUsers)
  // .put('/:id', usersController.update)
  .put('/:id', protect, usersController.update)
  .put('/updateProfil', uploadImg.singleUpload, usersController.updateProfil)
  .delete('/:id', protect, isAdmin, usersController.deleteUsers)
module.exports = Router
